version: '3.3'
services:
   db:
     image: mysql:8.0
     container_name: mysql-database
     volumes:
       - ./mysql-data:/var/lib/mysql
       - ./mysql-init-files:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myresto
       MYSQL_USER: webs
       MYSQL_PASSWORD: testPassword
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
   web:
    image: verkeur08/myresto:v2
    depends_on:
      - db
    ports:
      - '8082:8080'
    environment:
      MYSQL_LIEN: jdbc:mysql://mysql-database:3306/myresto
      MYSQL_DATABASE: myresto
      MYSQL_USER: webs
      MYSQL_PASSWORD: testPassword
volumes:
    db_vol:      
