version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_vol:/var/lib/mysql
       - ./sql:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myresto
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8084:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
   web: 
    depends_on:
      - db
    image: verkeur08/myresto:v1
    ports:
      - '8001:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myresto
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
volumes:
    db_vol:      


      